steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build-potal
  args: [
    'build',
    '-f', './docker/potal/Dockerfile',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/potal/potal:$COMMIT_SHA',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/potal/potal:latest',
    '.',
    ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: push-potal
  args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/potal/potal:$COMMIT_SHA']
  waitFor: ['build-potal']
- name: 'gcr.io/cloud-builders/docker'
  id: build-backend
  args: [
    'build',
    '-f', './docker/backend/Dockerfile',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:latest',
    '.',
    ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: push-backend
  args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA']
  waitFor: ['build-backend']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: deploy-potal
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'potal'
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/potal/potal:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  waitFor: ['push-potal']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: deploy-backend
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'backend'
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  waitFor: ['push-backend']
- name: 'gcr.io/cloud-builders/npm'
  id: 'npm-install'
  args: ['install', '--frozen-lock'] 
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/npm'
  id: 'build-assets'
  args: ['run', 'build']
  waitFor: ['npm-install']
  secretEnv: ['SENTRY_AUTH_TOKEN']
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/potal/potal:latest'
artifacts:
  objects:
    location: gs://gib-potato-assets/
    paths: 
    - 'webroot/assets/*'
    - 'webroot/.vite/manifest.json'
availableSecrets:
  secretManager:
  - versionName: projects/841923001753/secrets/sentry_auth_token/versions/1
    env: 'SENTRY_AUTH_TOKEN'
