steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './docker/potal/Dockerfile', '-t', '${LOCATION}-docker.pkg.dev/$PROJECT_ID/potal/potal:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './docker/backend/Dockerfile', '-t', '${LOCATION}-docker.pkg.dev/$PROJECT_ID/backend/backend:latest', '.']
images:
- '$LOCATION-docker.pkg.dev/$PROJECT_ID/backend/backend:latest'
- '$LOCATION-docker.pkg.dev/$PROJECT_ID/potal/potal:latest'
