version: '3.1'
services:
  web:
    build: docker/web
    environment:
        - APP_NAME
        - ENVIRONMENT
        - VERSION
        - DEBUG
        - APP_ENCODING
        - APP_DEFAULT_LOCALE
        - APP_DEFAULT_TIMEZONE
        - SECURITY_SALT
        - MAIN_DOMAIN
        - DATABASE_URL
        - SLACK_CLIENT_ID
        - SLACK_CLIENT_SECRET
        - SLACK_SIGNING_SECRET
        - SLACK_TEAM_ID
        - SLACK_REDIRECT_URI
        - SLACK_BOT_USER_OAUTH_TOKEN
        - SENTRY_DSN
        - SENTRY_MONITOR_ID
        - POTAL_TOKEN
        - POTATO_CHANNEL
        - POTATO_SLACK_USER_ID
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - .:/var/www/gib-potato:consistent
    networks:
      gib-potato:
        aliases:
          - gib-potato.test
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gib_potato
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      gib-potato:
        aliases:
          - db.gib-potato.test

volumes:
  db:

networks:
  gib-potato:
