version: '3.1'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    environment:
        - APP_NAME
        - ENVIRONMENT
        - RELEASE
        - DEBUG
        - APP_ENCODING
        - APP_DEFAULT_LOCALE
        - APP_DEFAULT_TIMEZONE
        - SECURITY_SALT
        - MAIN_DOMAIN
        - DATABASE_USER
        - DATABASE_PASSWORD
        - DATABASE_NAME
        - DATABASE_SOCKET
        - LOG_DEBUG_URL
        - LOG_ERROR_URL
        - SLACK_CLIENT_ID
        - SLACK_CLIENT_SECRET
        - SLACK_SIGNING_SECRET
        - SLACK_TEAM_ID
        - SLACK_REDIRECT_URI
        - SLACK_BOT_USER_OAUTH_TOKEN
        - SENTRY_BACKEND_DSN
        - SENTRY_FRONTEND_DSN
        - SENTRY_MONITOR_ID
        - POTAL_TOKEN
        - POTATO_CHANNEL
        - POTATO_SLACK_USER_ID
    depends_on:
      - db
      - potal
    ports:
      - 8080:8080
    networks:
      gib-potato:
        aliases:
          - gib-potato.test

  potal:
    build:
      context: .
      dockerfile: ./docker/potal/Dockerfile
    environment:
      - SENTRY_POTAL_DSN
      - RELEASE
      - ENVIRONMENT
      - SLACK_BOT_USER_OAUTH_TOKEN
      - SLACK_SIGNING_SECRET
      - POTAL_URL
      - POTAL_TOKEN
    ports:
      - 3000:3000
    networks:
      gib-potato:
        aliases:
          - potal.gib-potato.test

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: gib_potato
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 8432:5432
    networks:
      gib-potato:
        aliases:
          - db.gib-potato.test

volumes:
  db:

networks:
  gib-potato:
