version: '3.1'
services:
  web:
    build: docker/web
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - .:/var/www/gib-potato:consistent
    networks:
      gib-potato:
        aliases:
          - gib-potato.test
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gib_potato
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      gib-potato:
        aliases:
          - db.gib-potato.test

volumes:
  db:

networks:
  gib-potato:
