services:
  web:
    build: docker/web
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - .:/var/www/gib-potato:consistent
    networks:
      gib-potato:
        aliases:
          - gib-potato.test

  db:
    build: docker/mysql
    ports:
      - 8306:3306
    environment:
      MYSQL_DATABASE: gib_potato
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    networks:
      gib-potato:
        aliases:
          - db.gib-potato.test

volumes:
  db:

networks:
  gib-potato: