import SwiftUI
import Charts

struct ChartView: View {
    struct Entry: Identifiable {
        let hour: Double
        let value: Int

        var id: Double { hour }
    }

    let stock: StockDto

    var entries: [Entry] {
        guard let dataset = stock.data.datasets.first else { return [] }

        var hourCounts: [String: Int] = [:]
        let hourTotals: [String: Int] = stock.data.labels.reduce(into: [:]) { $0[$1, default: 0] += 1 }

        return zip(stock.data.labels, dataset.data).map { label, value in
            let count = hourCounts[label, default: 0]
            hourCounts[label] = count + 1
            let total = hourTotals[label, default: 1]
            let baseHour = Double(label) ?? 0
            let fractionalHour = baseHour + (Double(count) / Double(total))
            return Entry(hour: fractionalHour, value: value)
        }
    }

    var borderColor: Color {
        Color(hex: stock.data.datasets[0].borderColor)
    }

    var body: some View {
        Chart(entries) { entry in
            LineMark(
                x: .value("Hour", entry.hour),
                y: .value("Value", entry.value)
            )
            .interpolationMethod(.stepStart)
            .foregroundStyle(borderColor)
            .lineStyle(StrokeStyle(lineWidth: 1))
        }
        .chartXAxisLabel(position: .bottom, alignment: .center, spacing: nil) {
            Text("Time 🕒")
        }
        .chartYAxisLabel(position: .leading, alignment: .center, spacing: nil) {
            Text("Amount 🥔")
                .rotationEffect(.degrees(-180))
        }
    }
}

#Preview {
    ChartView(stock: .init(
        id: 1,
        symbol: "AMS",
        description: "Amsterdam",
        sharePrice: 130,
        stockInfo: StockInfoDto(
            amount: 130,
            open: 5,
            high: 130,
            low: 5,
            volume: 75,
            marketCap: 9750
        ),
        data: StockDataDto(
            labels: [
                "8",
                "8",
                "8",
                "8",
                "8",
                "8",
                "8",
                "8",
                "9",
                "9",
                "9",
                "9",
                "9",
                "9",
                "9",
                "9",
                "9",
                "9",
                "9",
                "9",
                "10",
                "10",
                "10",
                "10",
                "10",
                "10",
                "10",
                "10",
                "10",
                "10",
                "10",
                "10",
                "11",
                "11",
                "11",
                "11",
                "11",
                "11",
                "11",
                "11",
                "11",
                "11",
                "11",
                "11",
                "12",
                "12",
                "12",
                "12",
                "12",
                "12",
                "12",
                "12",
                "12",
                "12",
                "12",
                "12",
                "13",
                "13",
                "13",
                "13",
                "13",
                "13",
                "13",
                "13",
                "13",
                "13",
                "13",
                "13",
                "14",
                "14",
                "14",
                "14",
                "14",
                "14",
                "14",
                "14",
                "14",
                "14",
                "14",
                "14",
                "15",
                "15",
                "15",
                "15",
                "15",
                "15",
                "15",
                "15",
                "15",
                "15",
                "15",
                "15",
                "16",
                "16",
                "16",
                "16",
                "16",
                "16",
                "16",
                "16",
                "16",
                "16",
                "16",
                "16",
                "17",
                "17",
                "17",
                "17",
                "17",
                "17",
                "17",
                "17",
                "17",
                "17",
                "17",
                "17",
                "18",
                "18",
                "18",
                "18",
                "18",
                "18",
                "18",
                "18",
                "18",
                "18",
                "18",
                "18",
                "19",
                "19",
                "19",
                "19",
                "19",
                "19",
                "19",
                "19",
                "19",
                "19",
                "19",
                "19",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "20",
                "21",
                "21",
                "21",
                "21",
                "21",
                "21",
                "21",
                "21",
                "21",
                "21",
                "21",
                "21",
                "22",
                "22",
                "22",
                "22",
                "22",
                "22",
                "22",
                "22",
                "22",
                "22",
                "22",
                "22",
                "23",
                "23",
                "23",
                "23",
                "23",
                "23",
                "23",
                "23",
                "23",
                "23",
                "23",
                "23",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "1",
                "1",
                "1",
                "1",
                "1",
                "1",
                "1",
                "1",
                "1",
                "1",
                "1",
                "1",
                "2",
                "2",
                "2",
                "2",
                "2",
                "2",
                "2",
                "2",
                "2",
                "2",
                "2",
                "2",
                "3",
                "3",
                "3",
                "3",
                "3",
                "3",
                "3",
                "3",
                "3",
                "3",
                "3",
                "3",
                "4",
                "4",
                "4",
                "4",
                "4",
                "4",
                "4",
                "4",
                "4",
                "4",
                "4",
                "4",
                "5",
                "5",
                "5",
                "5",
                "5",
                "5",
                "5",
                "5",
                "5",
                "5",
                "5",
                "5",
                "6",
                "6",
                "6",
                "6",
                "6",
                "6",
                "6",
                "6",
                "6",
                "6",
                "6",
                "6",
                "7",
                "7",
                "7",
                "7",
                "7",
                "7",
                "7",
                "7",
                "7",
                "7",
                "7",
                "7",
                "8",
                "8",
                "8",
                "8"
            ],
            datasets: [
                StockDatasetDto(
                    data: [
                        5,
                        5,
                        5,
                        5,
                        5,
                        5,
                        5,
                        5,
                        5,
                        5,
                        6,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        10,
                        70,
                        70,
                        65,
                        65,
                        65,
                        90,
                        110,
                        110,
                        110,
                        110,
                        110,
                        110,
                        130,
                        130,
                        130,
                        130,
                        130,
                        130,
                        130,
                        130,
                        130,
                        130,
                        130,
                        130
                    ],
                    borderColor: "#22c55e",
                    backgroundColor: "rgba(34, 197, 94, 0.1)"
                )
            ]
        )))
}
