name: build-docker-images
on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - '*'

jobs:
    build-potal:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
            - name: Build Potal Docker image
              uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
              with:
                  context: .
                  file: ./docker/potal/Dockerfile
                  push: false

    build-backend:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
            - name: Build Backend Docker image
              uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
              with:
                  context: .
                  file: ./docker/backend/Dockerfile
                  push: false

    build-shopato:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
            - name: Build Backend Docker image
              uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
              with:
                  context: .
                  file: ./docker/shopato/Dockerfile
                  push: false
