name: "Go CI"

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  go-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        
    - name: Run build
      working-directory: ./potal
      run: go build . 
      
    - name: Run vet
      working-directory: ./potal
      run: go vet .
    
    - name: Run lint
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: ./potal
    
    - name: Run tests
      working-directory: ./potal
      run: go test -v -count=1 -race ./... -coverprofile=coverage.out -covermode=atomic

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        working-directory: ./potal
        token: ${{ secrets.CODECOV_TOKEN }}
