name: 'JS CI'

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - '*'

permissions:
    contents: read

jobs:
    js-ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7

            - uses: actions/setup-node@v6
              with:
                  node-version: '26'

            - name: Run npm install
              run: npm install

            - name: Run npx vp lint
              run: npx vp lint

            - name: Run npx vp fmt --check
              run: npx vp fmt --check

            - name: Run npm build
              run: npm run build
