name: 'JS CI'

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - '*'

permissions:
    contents: read

jobs:
    js-ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7

            - name: Run vp install
              run: vp install

            - name: Run vp lint
              run: vp lint

            - name: Run vp fmt --check
              run: vp fmt --check

            - name: Run vp build
              run: vp build
